### ISSUE TITLE
Курсовой проект за 10 семестр

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/lekaitow.github.io#1]
@aurusov
1 - Постановка задачи, А1:
https://lekaitow.github.io/10semester/10_1_A1.pdf

2 - Выбор графической библиотеки для подсистемы визуализации, А2:
https://lekaitow.github.io/10semester/10_2_A2.pdf

3 - Диаграмма активности формирования массива значений графика, А1:
https://lekaitow.github.io/10semester/10_3_A1.pdf

4 - Диаграмма активности интерфейса пользователя, А2:
https://lekaitow.github.io/10semester/10_4_A2.pdf

5 - Диаграмма классов подсистемы визуализации параметров, А1:
https://lekaitow.github.io/10semester/10_5_A1.pdf

6 - Диаграмма последовательности работы с графиком, А2:
https://lekaitow.github.io/10semester/10_6_A2.pdf

~~7 - Диаграмма использования, А3~~

~~8 - Исследования, выбор библиотеки - объединено с 2~~

9 - Результаты работы, А1:
https://lekaitow.github.io/10semester/10_9_A1.pdf

10 - Штампы 1, 2 и 9 листов:
https://lekaitow.github.io/10semester/1-2-9.pdf

11 - Пояснительная записка:
https://lekaitow.github.io/10semester/report.docx
https://lekaitow.github.io/10semester/report.pdf

Все листы одним файлом:
https://lekaitow.github.io/10semester/10_all.pdf

Исходники листов:
https://lekaitow.github.io/10semester/10_raw.zip

**Comment by aurusov** [comment]
:one: Постановка задачи, А1 **[на печать]**
:two: Исследования, графики быстродействия, А2 **[на печать]**
:three: Диаграмма активности формирования массива значений графика, А1 **[на печать]**
:four: Диаграмма активности интерфейса пользователя, А2 **[на печать]**
:five: Диаграмма классов подсистемы визуализации параметров, A1 **[на печать]**
:six: Диаграмма последовательности работы с графиком, А2 **[на печать]**
:seven: ~~Диаграмма использования, А3~~
- Делать не надо

:eight: ~~Исследования, выбор библиотеки~~
- Объеденили с :two: 

:nine: Результаты, экранные формы, A1 **[на печать]**

:keycap_ten: Штампы 1, 2 и 9 листов **[на печать]**

**Comment by LeKaitoW** [comment]
:three:

> Название не устраивает, какой-то непонятный массив значений. Может так `Диаграмма активности создания массива значений графика` ? Обсуждаемо, предложи свой вариант.

Изначально оно так и было, меня смутило слово `создание`, казалось, что `формирование` или `подготовка (данных)` здесь подходит больше.

> Все ветви заканчиваются блоком `Записать индекс в список` - он общий ? Если да, то удали копии, сведи к одному блоку.
> `Записать номер точки в список` - это что за список ? Блок повторятеся трижды в конце, очень похоже на пред. случай.

Список общий, ок.

> `Записать индекс в список` - зачем в него записывать индекс ?

Используется при построении в процессе прогона, при появлении новых данных.

> `Записать последнее значение count` - почему обрабатывается отдельно ? Если это подход такой, чтобы в конце была горизонтальная черта у графика, то почему не сделать тоже самое для других графигов, например, для enum ?

В базе данных просто не хранится количество одновременно запущенных образцов, поэтому приходится хранить последнее значение в мапе.

:four: 

> Как я понял, связь с пред. диаграммой в блоке '''Добавить точку в dataset'''. Правильно ? Если да, то назвать и диаграмму и блок надо одинаково.

Связь с предыдущей диаграммой в блоках `Считать данные из базы данных` и `Получить координаты точки из записи базы данных`. Думаю, их надо объединить. Или заменить: сделать блок `Получить координаты точек`, `Добавить точки в dataset`, а цикл про наличие точек убрать.

:five: 
Классы: `PlotDataParser`, `PlotItem`, `RDOPlotView`, `RDOChartComposite` и 2 метода в `RDOSerializedObjectsView`.

> Это да, но я не нашёл где :smile:

Просто подвигать надписи, красоту навести. :)

**Comment by aurusov** [comment]
:three: 

> Изначально оно так и было, меня смутило слово создание, казалось, что формирование или подготовка (данных) здесь подходит больше.

Это можно оставить, главное добавить `графика` в конце. Обновил в общей теме.

> > Записать индекс в список - зачем в него записывать индекс ?
> 
> Используется при построении в процессе прогона, при появлении новых данных.

Всеравно непонятно. Надо обсудить голосом.

> > Записать последнее значение count - почему обрабатывается отдельно ? Если это подход такой, чтобы в конце была горизонтальная черта у графика, то почему не сделать тоже самое для других графигов, например, для enum ?
> 
> В базе данных просто не хранится количество одновременно запущенных образцов, поэтому приходится хранить последнее значение в мапе.

Вопрос не про хранение, а про момент добавления точки в dataset. Почему последняя точка оказалась избранной (обрабатывается не как все) ?

**Comment by aurusov** [comment]
:four: 

> ...Думаю, их надо объединить. Или заменить...

А нельзя всё это заменить на блок с именем первой диаграммы ? Типа вызов подпрограммы. Или это не так ?

**Comment by LeKaitoW** [comment]
> Вопрос не про хранение, а про момент добавления точки в dataset. Почему последняя точка оказалась избранной (обрабатывается не как все) ?

Чтобы при появлении новых данных строить график с этого значения, а не с 0. Это не про последнюю точку, а про последнее значение `count` при выходе из цикла.

:four:

> А нельзя всё это заменить на блок с именем первой диаграммы ? Типа вызов подпрограммы. Или это не так ?

Именно так и есть, исправлю.

**Comment by aurusov** [comment]
> Это не про последнюю точку, а про последнее значение count при выходе из цикла.

ok

**Comment by aurusov** [comment]
Обновил итоговую страницу, удалил снятые вопросы.

**Comment by LeKaitoW** [comment]
:three: 
Удалила повторяющиеся блоки про `Записать номер точки в список` и объединила с блоком про индекс. Может, так лучше?
(Под списком тут имеется в виду мапа, которая хранит индекс и номер последней точки.)

:four: 
Исправила.

**Comment by aurusov** [comment]
:three: 
Выглядит ok. Но всеравно у меня впрос: зачем запоминать номер точки для соответствующего индекса в список ? Попробуй ответить письменно, хотя мне кажется, что это надо обсуждать голосом. Если тут есть косяк, то скорее всего будем исправлять его после защиты. Но прояснить ситуацию всетаки хочется.

**Comment by aurusov** [comment]
Обновил итого

**Comment by LeKaitoW** [comment]
:three: 
1. Индекс - чтобы не открывать один и тот же график много раз (если в мапе есть индекс, то делать окно с данным графиком активным).
2. Номер точки - чтобы при построении графика в процессе прогона или при получении новых данных начинать/продолжать парсить данные для графика с последней построенной точки, а не с самого начала.

**Comment by LeKaitoW** [comment]
:one:
Обновила первый лист.

**Comment by aurusov** [comment]
:three: 
Во, теперь понял.

**Comment by aurusov** [comment]
:one: 
Давай так оставим

**Comment by aurusov** [comment]
Обновил итого

**Comment by LeKaitoW** [comment]
:nine: 
Добавила лист результатов.
https://lekaitow.github.io/10semester/10_9_A1.pdf

**Comment by aurusov** [comment]
:nine: 

![2015-05-21 11-16-18 2](https://cloud.githubusercontent.com/assets/5585202/7744445/f0053250-ffab-11e4-984b-6dc74b7fb491.png)

**Comment by LeKaitoW** [comment]
:nine:
Обновила.
Кажется, что нужно уменьшить верхние графики?
Сделаю вариант, чтобы все графики были одного размера.

**Comment by aurusov** [comment]
:nine:
давай

**Comment by LeKaitoW** [comment]
:nine: 
https://lekaitow.github.io/10semester/10_9_A1_2.pdf

**Comment by aurusov** [comment]
:nine:
Небольшое замечание. Средний случай. На правом графике можно выделить первоначальную область. Но тогда надо будет сделать тоже самое и на нижнем примере с масштабом. А можно указкой на защите тыкнуть и словами сказать. В общем я за то, чтобы оставить скрины как есть, без фотошопа. А в докладе про это упомянуть, если будет желание.

**Comment by LeKaitoW** [comment]
:nine: 
Мне вообще не очень нравится что-то рисовать поверх скринов. Конечно, можно наставить стрелочек и расписать всё (про изменения осей и т.д.). Но как мне кажется, лучше указкой тыкать.
Тогда из репозитория первый вариант удалить?

**Comment by aurusov** [comment]
:nine: 
Да, удалять. Не заметил, что это в другом файле.

**Comment by LeKaitoW** [comment]
:six: 
Вопрос про диаграмму последовательности. Можно рассматривать как взаимодействие пользователя с меню и т.д., а можно рассмотреть взаимодействие классов. Так какую лучше изобразить?
Наверное, стоит делать первый вариант - про второй уже и в диаграмме классов, и в диаграмме активности говорится.

**Comment by aurusov** [comment]
:six: 
Наверху всеравно будет список объектов (классов), у которых вызываться методы. Как будет выглядеть пользователь на такой схеме ?

**Comment by LeKaitoW** [comment]
:six: 
Поняла, мне просто попался не очень удачный пример такой диаграммы. Там был указан пользователь как класс.

**Comment by LeKaitoW** [comment]
:two:, :eight: 
Может, объединить в один лист?
При этом в таблице выбора библиотеки JFreeChart рассмотреть 3 раза (с SWT, AWT и бриджем - где-то будут галочки про встраивание в эклипс, а где-то нет.)
И получится А2: слева таблица с библиотеками, справа - графики.

:six: 
Добавила диаграмму последовательностей.
https://lekaitow.github.io/10semester/10_6_A2.pdf

:seven: 
А стоит ли делать диаграмму использования? Кажется, что даже на А3 набрать не получится.

**Comment by aurusov** [comment]
:two: :eight:
Можно. Ты хочешь плакат с одним общим штампом ?

**Comment by aurusov** [comment]
:seven: 
Стоит. Если не на листы, то в записку вставишь и напишешь пару абзацев.

**Comment by aurusov** [comment]
:six: 
Обновил итого

**Comment by LeKaitoW** [comment]
:two: , :eight: 
Да.

:six:
При закрытии РДО. Получается, стрелочка с delete не нужна, достаточно только крестика.
Или не учитывать закрытие РДО и ничего не удалять?

:seven:
Хорошо.

**Comment by aurusov** [comment]
:six: 
А почему при закрытии не вызывается для всех графиков `RDOStopAction()` ? Это упростит код и снимет вопросы по листу.

**Comment by LeKaitoW** [comment]
:six: 
Обновила диаграмму.
Теперь обрабатывается два вызова `close()` - закрытие окошка с деревом сериализуемых объектов и закрытие окошка с графиком.
При этом класс `PlotDataParser` статический - удаляться не будет.

**Comment by aurusov** [comment]
:six: 
Ну насчет статического я бы поспорил. Но давай отложим до консультации, а там, если не забудем, поговорим. По листу. Как я понял, методы `clicked()` приходят от юзера в разные окошки и по разному обрабатываются. Правильно ? С методом `close()` тоже самое ?

**Comment by aurusov** [comment]
> С методом close() тоже самое ?

Имеется в виду нажатие на крестик

**Comment by LeKaitoW** [comment]
Да, это как раз нажатие на крестик.

**Comment by aurusov** [comment]
:six: 
Тогда осталось разобраться с темой.  `Диаграмма последовательности создания графика` не вяжется с `close()`. Предложи другое название.

**Comment by LeKaitoW** [comment]
:six: 
`Диаграмма последовательности работы с графиком`?

**Comment by aurusov** [comment]
:seven: 
Пересчитал кол-во А1, понял, что лист явно лишний. Начала уже ?

**Comment by LeKaitoW** [comment]
:seven: 
Нет, не начинала.

**Comment by aurusov** [comment]
:seven: 
Ну и нафиг его

**Comment by aurusov** [comment]
:six: 
Да

**Comment by LeKaitoW** [comment]
:six: , :seven: 
Ок.

**Comment by LeKaitoW** [comment]
:six: 
Обновила название листа.

**Comment by aurusov** [comment]
:six:
Обновил итого. Последний лист :)

**Comment by LeKaitoW** [comment]
:two: 
Добавила лист выбора библиотеки.
https://lekaitow.github.io/10semester/10_2_A2.pdf

**Comment by aurusov** [comment]
Посчитал кол-во листов, получилось 6 А1. Правильно ?

**Comment by LeKaitoW** [comment]
Нет, пять с половиной. Второй лист (исследования) - А2.

**Comment by aurusov** [comment]
До защиты я хотел бы по диагонали посмотреть записку.

**Comment by LeKaitoW** [comment]
Там осталось только апробирование и заключение дописать.
https://lekaitow.github.io/10semester/report.docx
Сегодня допишу и залью в pdf.

**Comment by LeKaitoW** [comment]
Добавила записку в pdf: https://lekaitow.github.io/10semester/report.pdf
И исходники листов.

**Comment by aurusov** [comment]
Записка ok

**Comment by LeKaitoW** [comment]
Добавила все листы одним файлом:
https://lekaitow.github.io/10semester/10_all.pdf

Нужно ли что-то ещё выкладывать или можно закрывать таску?

**Comment by aurusov** [comment]
Закрывай

**Comment by aurusov** [comment]
Хотя стоп. Добавь штампы к всем листам.

**Comment by LeKaitoW** [comment]
Добавила.

**Comment by aurusov** [comment]
Выложил http://aurusov.github.io/rdo_diploma/
