### ISSUE TITLE
Пятнашки.

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/lekaitow.github.io#2]
1. [Постановка задачи (А1)](https://lekaitow.github.io/game%205/game5_1_A1.pdf)
2. [Диаграмма состояний плагина (А1)](https://lekaitow.github.io/game%205/game5_2_A1.pdf)
3. [Диаграмма классов плагина (А1)](https://lekaitow.github.io/game 5/game5_3_A1.pdf)
4. [Алгоритм формирования начального положения фишек (А1)](https://lekaitow.github.io/game%205/game5_4_A1.pdf)
5. [Результаты работы (А1)](https://lekaitow.github.io/game%205/game5_5_A1.pdf)
6. ~~Диаграмма компонентов (А3) (?)~~
7. [Штампы (А4)](https://lekaitow.github.io/game%205/stamps1-5.pdf)
8. [Пояснительная записка](https://lekaitow.github.io/game%205/game5_report.pdf)

[Исходники](https://github.com/LeKaitoW/lekaitow.github.io/blob/master/game%205/game%205_raw.rar)

[Все листы одним файлом](https://lekaitow.github.io/game%205/game5_raw.zip)

**Comment by LeKaitoW** [comment]
@aurusov
Прошу посмотреть 2 и 4 листы, как будет возможность.

**Comment by aurusov** [comment]
1. Постановка задачи (А1) **[на печать]**
2. Диаграмма состояний плагина (А1) **[на печать]**
3. Диаграмма классов плагина (А1) **[на печать]**
4. Блок-схема генерации начального положения фишек (А1) **[на печать]**
5. Результаты работы (А1) **[на печать]**
6. Штампы на плакаты **[на печать]**
7. ПЗ **[на печать]**

**Comment by LeKaitoW** [comment]
Штампам. Поправила.
1. 20

4.
- 20
- Ок, поправлю.
- Ок, поправлю.

**Comment by LeKaitoW** [comment]
UPD.
Добавлен лист 3.
Исправлен лист 4.
Добавлен лист 5.

**Comment by LeKaitoW** [comment]
UPD.
Добавлен лист 1.

**Comment by aurusov** [comment]
Обновил

**Comment by LeKaitoW** [comment]
1.

> Управление алгоритмом "смены родителя" - это про что ?

Про галочку в диалоговом окне: `Traverse graph`
4. Эта вода придумывалась 3 дня, сложно так просто с ней расстаться. :)

**Comment by LeKaitoW** [comment]
> Генерация случайным образом решаемых раскладок

Может быть "решаемых и не решаемых раскладок"? Можно ещё приписать а-ля "в зависимости от заданных условий".

**Comment by LeKaitoW** [comment]
UPD.
Поправила лист 1.
Добавила штампы.
Переименовала лист 3 в шапке.

**Comment by LeKaitoW** [comment]
UPD:
Исправлен лист 1.
Добавлена записка.

**Comment by aurusov** [comment]
Записка, ТЗ

```
Плагин Игра 5 должен удовлетворять следующим требованиям: 
• Задание начального расположения фишек различными способами 
• Генерация случайным образом решаемых раскладок
• Изменение стоимости правил 
• Переключение между эвристиками 
• Автоматическая генерация исходного текста модели 
• Отображение текущего состояния поля при выборе вершины графа 
• Изменение настроек алгоритма А* 
• Создание проекта с помощью визарда 
• Интеграция в Rao X 
```

**Comment by aurusov** [comment]
```
3.6.    Стадии и этапы разработки
Плановый срок начала разработки – 20 июня 2015г. 
Плановый срок окончания разработки –  26 сентября 2015г. 
```

Это что ?

**Comment by aurusov** [comment]
В 6-ой главе хочется видеть скрины описываемых в тексте компонент. Как минимум два - диалог и визард.

**Comment by aurusov** [comment]
```
8.  Заключение
...
• Разработан визард создания проектА.
...
• Разработанный плагин использовался для проведения лабораторной работу по курсу Моделирование дискретных производственных процессов. 

```

**Comment by aurusov** [comment]
```
Список используемых источников
1.  Емельянов В.В., Ясиновский С.И. Введение в интеллектуальное имитационное моделирование сложных дискретных систем и процессов. 
Язык РДО. - М.: "Анвик", 1998. - 427 с., ил. 136. 
```

Где в работе использовалась эта книга ?

**Comment by LeKaitoW** [comment]
> Это что ?

Вроде не соврала в датах. Начала писать плагин в конце июня. Вот с окончанием промахнулась, там скорее 30 сентября, если верить гитхабу. :(

> Где в работе использовалась эта книга ?

В введении ПЗ.

**Comment by LeKaitoW** [comment]
UPD: исправила все замечания по ПЗ

**Comment by aurusov** [comment]
> В введении ПЗ.

Выглядит как сноска. Сейчас так принято или косяк ?

**Comment by LeKaitoW** [comment]
> Выглядит как сноска. Сейчас так принято или косяк ?

Гост говорит про внутритекстовые, подстрочные (сноски) и затекстовые (что подразумевалось в ПЗ) ссылки.
"Затекстовая ссылка визуально разделена с текстом документа.  Порядковый номер  библиографической записи в затекстовой ссылке указывают в знаке выноски на верхней линии шрифта или в отсылке, которую приводят в квадратных скобках в строку с текстом документа."
Получилось и то, и то, значит, косяк.
Уже исправила.

**Comment by LeKaitoW** [comment]
[Исходники](https://github.com/LeKaitoW/lekaitow.github.io/blob/master/game%205/game%205_raw.rar)
[Все листы одним файлом](https://lekaitow.github.io/game%205/game5_all.pdf)
