### ISSUE TITLE
Процессный подход (курсовой проект)

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/lekaitow.github.io#3]
1. [Постановка задачи (А1)](https://lekaitow.github.io/process/process_1_A1.pdf)
2. [Диаграмма классов процессного подхода (А1)](https://lekaitow.github.io/process/process_2_A1.pdf)
3. [Диаграмма последовательности вызова для теста с ветвлением (А1)](https://lekaitow.github.io/process/process_3_A1.pdf)
4. [Диаграммы активности для блоков (часть 1)](https://lekaitow.github.io/process/process_4_A1.pdf)
   - Диаграмма активности блока Generate (A3)
   - Диаграмма активности блока Terminate (A3)
   - Диаграмма активности блока Seize (A3)
   - Диаграмма активности блока Release (A3)
5. [Диаграммы активности для блоков (часть 2)](https://lekaitow.github.io/process/process_5_A2.pdf)
   - Диаграмма активности блока Queue (A3)
   - Диаграмма активности блока Test (A3)
6. [Результаты работы (А1)](https://lekaitow.github.io/process/process_6_A1.pdf)
7. ~~Диаграмма компонентов (А3)~~
8. [Штампы 1 и 6 листов](https://lekaitow.github.io/process/stamps1-6.pdf)
9. [Пояснительная записка](https://lekaitow.github.io/process/report.pdf)

**Comment by LeKaitoW** [comment]
@aurusov
Прошу посмотреть диаграммы.

**Comment by aurusov** [comment]
1. Постановка задачи (А1) **[на печать]**
2. Диаграмма классов процессного подхода (А1) **[на печать]**
3. Диаграмма последовательности вызова для теста с ветвлением (А1) **[на печать]**
4. Диаграммы активности для блоков (А1) **[на печать]**
5. Диаграммы активности для блоков (А2) **[на печать]**
6. Результаты (А1) **[на печать]**
7. Штампы **[на печать]**
8. РПЗ **[на печать]**

**Comment by LeKaitoW** [comment]
> какой размер у листа ?

А2. То есть, каждая диаграмма по А3.

**Comment by LeKaitoW** [comment]
Перечислила все диаграммы по отдельности.

**Comment by LeKaitoW** [comment]
UPD: добавлены заготовки 3 и 6.
Добавлен лист 1.

**Comment by LeKaitoW** [comment]
UPD: Обновлены листы 3 и 6.

>  сделать цвета в парах одинаковыми (generate + terminate, sieze + release)

Блоку terminate изменила форму для большей схожести с generate.

**Comment by aurusov** [comment]
обновил

**Comment by LeKaitoW** [comment]
UPD: добавила штампы и записку (неполную)

**Comment by aurusov** [comment]
обновил

**Comment by aurusov** [comment]
обновил
