### ISSUE TITLE
Диплом

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/lekaitow.github.io#4]
1. **[Постановка задачи](https://lekaitow.github.io/diploma/1_diploma_A1.pdf) - A1**
2. **[Диаграмма классов процессного подхода](https://lekaitow.github.io/diploma/2_lib_class_A1.pdf) - А1**
3. **[Диаграммы активности (Generate, Terminate, Seize, Release)](https://lekaitow.github.io/diploma/3_activity_blocks_A1.pdf) - А3+А3+А3+А3**
4. **[Диаграммы активности (SelectPath, Queue)](https://lekaitow.github.io/diploma/4_activity_blocks_A2.pdf) - А3+А3**
5. **[Диаграммы пакетов](https://lekaitow.github.io/diploma/5_package_rao_editor_A1.pdf) - А2+А2**
6. **[Диаграмма классов графического редактора](https://lekaitow.github.io/diploma/6_graph_class_A1.pdf) - А1**
7. **[Исследовательская часть](https://lekaitow.github.io/diploma/7_gpss_A1.pdf) - A1**
8. **[Диаграмма активности формирования строк трассировки процессного подхода](https://lekaitow.github.io/diploma/8_trace_A2.pdf) - А2**
9. **[Выбор графической библиотеки](https://lekaitow.github.io/diploma/9_gef_A1.pdf) - A1**
10. **[Внешний вид подсистемы процессного подхода](https://lekaitow.github.io/diploma/10_screen_A1.pdf) - A1**
11. **[Диаграмма состояний подсистемы процессного подхода](https://lekaitow.github.io/diploma/11_state_A2.pdf) - А2**
12. **[Диаграмма целей](https://lekaitow.github.io/diploma/12_goal_A2.pdf) - А2**
13. **[Диаграмма последовательности](https://lekaitow.github.io/diploma/13_sequence_A1.pdf) - А1**
14. **[Результаты работы](https://lekaitow.github.io/diploma/14_result_A1.pdf) - А1**

**[Штампы](https://lekaitow.github.io/diploma/stamps.pdf)**
**[Записка](https://lekaitow.github.io/diploma/diploma.pdf)**
**[Рецензия](https://lekaitow.github.io/diploma/рецензия.pdf)**

**Comment by LeKaitoW** [comment]
@aurusov
Посмотрите залитые листы, пожалуйста

**Comment by aurusov** [comment]
1. Постановка задачи - А1, ok, **[на печать]**
2. Диаграмма классов процессного подхода - А1, ok, **[на печать]**
3. Диаграммы активности (Generate, Terminate, Seize, Release) - А3+А3+А3+А3, **[на печать]**
4. Диаграммы активности (SelectPath, Queue) - А3+А3, **[на печать]**
5. Диаграммы пакетов - А2+А2, ok, **[на печать]**
6. Диаграмма классов графического редактора - А1, ok, **[на печать]**
7. Исследовательская часть - A1, ok, **[на печать]**
8. Диаграмма активности формирования строк трассировки процессного подхода - А2, ok, **[на печать]**
9. Выбор графической библиотеки - A1, ok, **[на печать]**
10. Внешний вид подсистемы процессного подхода - A1, ok, **[на печать]**
11. Диаграммы состояний подсистемы процессного подхода - А2, ok, **[на печать]**
12. Диаграмма целей - А2, ok, **[на печать]**
13. Диаграмма последовательности - А1, ok, **[на печать]**
14. Результаты работы - А1, ok, **[на печать]**

Штампы, ok, **[на печать]**
Записка, ok, **[на печать]**
Рецензия, ok, **[на печать]**

**Comment by LeKaitoW** [comment]
3 . Диаграммы активности (Generate, Terminate, Seize, Release) - А3+А3+А3+А3
- `generate`
  - (в процессе)
  - Очень хочется слово `записи`, но, может, в данном случае можно использовать `события`? Потому что все процессные записи в бд представляют собой время моделирования и имя блока.

4 . Диаграммы активности (SelectPath, Queue) - А3+А3
- `select path`
  - Я думала в оставшийся А2 сделать алгоритм конвертера (графические блоки в либовские), но можно и этот общий алгоритм показать.
- `queue`
  - Мы ведь проверяем до продвижения модельного времени. То есть, в один и тот же момент времени один транзакт выходит, другой заходит. Не похоже на ошибку. Единственное, что меня смущает -- мы получаем рантайм эррор без сообщения, пользователь не поймет, из-за чего он случился и как от него избавиться. Обсуждала этот момент @bogachev-pa, решить эту проблему можно рефакторингом симулятора -- заставлять в рантайм эррорах выводить сообщения о подобных ошибках.

**Comment by aurusov** [comment]
Обновил. Ответь на все вопросы, а то в прошлый раз часть без ответов осталась.

**Comment by LeKaitoW** [comment]
Обновила, ответила!

**Comment by aurusov** [comment]
> Очень хочется слово записи, но, может, в данном случае можно использовать события? Потому что все процессные записи в бд представляют собой время моделирования и имя блока.

`Сохранить состояния блока в базе данных` ?

**Comment by aurusov** [comment]
> Я думала в оставшийся А2 сделать алгоритм конвертера (графические блоки в либовские), но можно и этот общий алгоритм показать.

Тоже можно. Исходил из того, что у комиссии возникнет тот же вопрос, что и у меня.

**Comment by aurusov** [comment]
> Мы ведь проверяем до продвижения модельного времени. То есть, в один и тот же момент времени один транзакт выходит, другой заходит. Не похоже на ошибку. Единственное, что меня смущает -- мы получаем рантайм эррор без сообщения, пользователь не поймет, из-за чего он случился и как от него избавиться. Обсуждала этот момент @bogachev-pa, решить эту проблему можно рефакторингом симулятора -- заставлять в рантайм эррорах выводить сообщения о подобных ошибках.

Это надо обсудить голосом. Заведи таску, чтобы не забыть.

**Comment by LeKaitoW** [comment]
> Сохранить состояния блока в базе данных ?

Я бы не назвала это состоянием, потому что с блоком ничего не происходит. Он скорее говорит `сделал в 10.0 транзакт`. То есть, какое-то `событие`, `действие` (`момент`?) процессного подхода. Но подходят ли эти слова?

> Это надо обсудить голосом. Заведи таску, чтобы не забыть.

Таску завела.

Добавила листы 7,8 и записку (точнее, 80% от нее).

**Comment by LeKaitoW** [comment]
> Тоже можно. Исходил из того, что у комиссии возникнет тот же вопрос, что и у меня.

Общий алгоритм покажу на диаграмме последовательностей -- он довольно маленький, на самостоятельный А2 не потянет, а в большую диаграмму должен хорошо вписаться.

**Comment by LeKaitoW** [comment]
Добавила лист 9. Выбор графической библиотеки

**Comment by aurusov** [comment]
По записке отписался выше, по сути норм.

**Comment by aurusov** [comment]
> Я бы не назвала это состоянием, потому что с блоком ничего не происходит. Он скорее говорит сделал в 10.0 транзакт. То есть, какое-то событие, действие (момент?) процессного подхода. Но подходят ли эти слова?

Событие лучше не трогать. `Запротоколировать срабатывание блока` ?

**Comment by aurusov** [comment]
> > Это надо обсудить голосом. Заведи таску, чтобы не забыть.
> 
> Таску завела.

И где она ?

**Comment by LeKaitoW** [comment]
> И где она ?

https://github.com/aurusov/raox/issues/397
Забыла поставить на себя.
Не стала ставить milestone, потому что не только для процессного подхода может быть такая ситуация. Или все же поставить?

**Comment by aurusov** [comment]
Эта таска не совсем про то. Отписался в ней.

**Comment by LeKaitoW** [comment]
Добавила лист 10, поправила записку

**Comment by LeKaitoW** [comment]
Добавила рецензию

**Comment by aurusov** [comment]
Посмотрел

**Comment by LeKaitoW** [comment]
Добавила лист 11, позже залью исправления листов

> Заведи тикеты для недостатков

Завела. Объединила 1 со 2 и 4 с 5 недостатки. Для автоконнекшенов таска есть.

**Comment by aurusov** [comment]
1 и 2 совсем про разное, их нельзя смешивать. Переделал.

**Comment by LeKaitoW** [comment]
11 . Обновила ссылку

**Comment by aurusov** [comment]
Посмотрел

**Comment by aurusov** [comment]
> Или все же поставить?

Поставил

**Comment by LeKaitoW** [comment]
Обновила листы 3 и 4. Заменила у всех блоков про базу данных.
Добавила лист 14. Результаты работы.
Про 11 лист:

> Что ты хочешь этим сказать ? Что содержимое листа не соответствует фактическому коду ?

Соответствует, я просто поленилась делать все блоки диаграммы заново, поэтому скопипастила подходящие из пятнашек и добавила про редактор.

**Comment by aurusov** [comment]
> Соответствует, я просто поленилась делать все блоки диаграммы заново, поэтому скопипастила подходящие из пятнашек и добавила про редактор.

Норм

**Comment by aurusov** [comment]
> Добавила лист 14. Результаты работы.

QR-code должен вести на главную репу. Не настаиваю.

**Comment by LeKaitoW** [comment]
Обновила лист 8, добавила 12. Диаграмма целей

**Comment by aurusov** [comment]
Не забывай про https://github.com/aurusov/raox/issues/397. Ответы на эти вопросы актуальны для защиты.

**Comment by aurusov** [comment]
Посмотрел

**Comment by LeKaitoW** [comment]
> Не забывай про aurusov/raox#397. Ответы на эти вопросы актуальны для защиты.

Отписалась.

При диаграмму целей:

> Не жирно на А2 ?

Опиралась на старые дипломы, спрашивала у одногруппников. У кого-то планируется лист А1 с 11 целями! 10 на А2 показались не жирными.
Обновила цели. `средств` -> `средства`, пририсовала стрелочки.

**Comment by LeKaitoW** [comment]
Добавила 13 лист

**Comment by aurusov** [comment]
> У кого-то планируется лист А1 с 11 целями!

Это не показатель адекватности. У кого-то и 3 может быть на А1. У него свой научник, нам то что ? Но хорошо, пусть у нас будет А2.

**Comment by aurusov** [comment]
Посмотрел

**Comment by LeKaitoW** [comment]
> Это не показатель адекватности. У кого-то и 3 может быть на А1. У него свой научник, нам то что ? Но хорошо, пусть у нас будет А2.

Не спорю! Но и сильно выделяться "космическим кораблем" в дипломе не хочется. :)

Добавила первый лист!

**Comment by aurusov** [comment]
Норм

**Comment by LeKaitoW** [comment]
Залила окончательную версию записки. (С пропусками под задание, план, направление)
Прошу посмотреть аннотацию (стр. 10), т.к. необходима ее копия с вашей подписью.

**Comment by aurusov** [comment]
Аннотацию посмотрел. Увидел, что замечания исправила. Что еще изменилось в записке ?

**Comment by LeKaitoW** [comment]
До и после каждой формулы добавились пустые строки... (Интересные требования нормоконтроля)

**Comment by LeKaitoW** [comment]
UPD: Перенесла аннотацию до содержания, обновила содержание.
Теперь точно все правила и бюрократия соблюдены.

**Comment by LeKaitoW** [comment]
Добавила штампы

**Comment by aurusov** [comment]
Вроде всё, можно печатать.

**Comment by LeKaitoW** [comment]
Ура!

**Comment by LeKaitoW** [comment]
Добавила [все листы одним файлом](https://lekaitow.github.io/diploma/all.pdf) (в порядке, в котором рассказывала на защите).
И засунула фотки титулов в [записку](https://lekaitow.github.io/diploma/diploma.pdf), получилось довольно пиксельно.

**Comment by aurusov** [comment]
Выложил, http://raox.ru/?p=1243
